import { StyleSheet, Platform } from 'react-native';
import { AppColors } from '../../constants/Colors';

export const styles = StyleSheet.create({
  errorMessage: {
    color: AppColors.error, 
    textAlign: 'center',
    marginBottom: 15,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Inter',
    },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100%',
    backgroundColor: AppColors.background,
  },
  formContainer: {
    backgroundColor: AppColors.card,
    borderRadius: 20,
    padding: 30,
    width: '90%',
    maxWidth: 400,
    shadowColor: AppColors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    borderWidth: 1,
    borderColor: AppColors.border,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: AppColors.textPrimary,
    marginTop: 16,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  subtitle: {
    fontSize: 14,
    color: AppColors.textSecondary,
    textAlign: 'center',
    fontFamily: 'Inter',
  },
  form: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: AppColors.textPrimary,
    marginBottom: 8,
    fontFamily: 'Inter',
  },
  input: {
    borderWidth: 1,
    borderColor: AppColors.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    backgroundColor: AppColors.background,
    color: AppColors.textPrimary,
    fontFamily: 'Inter',
  },
  passwordContainer: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: 50,
  },
  passwordToggle: {
    position: 'absolute',
    right: 14,
    top: 14,
  },
  submitButton: {
    marginTop: 24,
    borderRadius: 25,
    overflow: 'hidden',
  },
  submitGradient: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  submitText: {
    color: AppColors.textLight,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    gap: 4,
  },
  toggleText: {
    fontSize: 14,
    color: AppColors.textSecondary,
    fontFamily: 'Inter',
  },
  toggleLink: {
    fontSize: 14,
    color: AppColors.primary,
    fontWeight: '600',
    fontFamily: 'Inter',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: AppColors.divider,
  },
  dividerText: {
    marginHorizontal: 16,
    fontSize: 12,
    color: AppColors.textSecondary,
    fontFamily: 'Inter',
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: AppColors.border,
    borderRadius: 12,
    backgroundColor: AppColors.background,
  },
  socialButtonText: {
    fontSize: 16,
    color: AppColors.textPrimary,
    fontWeight: '500',
    fontFamily: 'Inter',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
    alignSelf: 'center',
  },
  backText: {
    fontSize: 14,
    color: AppColors.textSecondary,
    fontFamily: 'Inter',
  },
});